# Generated by Django 6.0.1 on 2026-01-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_carspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoNews', max_length=100)),
                ('site_description', models.TextField(default='Your source for automotive news and reviews')),
                ('contact_email', models.EmailField(default='admin@autonews.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('default_meta_description', models.CharField(blank=True, max_length=160)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID', max_length=50)),
                ('google_adsense_id', models.CharField(blank=True, help_text='ca-pub-XXXXXX', max_length=50)),
                ('footer_text', models.TextField(default='© 2026 AutoNews. All rights reserved.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
