"""
Django settings for auto_news_site project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
# .env = base config (Docker hostnames like postgres, redis)
# .env.local = local overrides (127.0.0.1:5433 etc.) — only exists outside Docker
load_dotenv(BASE_DIR / '.env')
if not os.getenv('RUNNING_IN_DOCKER'):
    load_dotenv(BASE_DIR / '.env.local', override=True)

# Sentry Configuration
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.1,  # 10% транзакций для production
        profiles_sample_rate=0.1,
        environment=os.getenv('ENVIRONMENT', 'development'),
        send_default_pii=False,  # Не отправлять личные данные
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-immediately')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Internationalization
LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Allowed hosts - includes custom domain
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') + [
    'freshmotors.net',
    'www.freshmotors.net',
    'api.freshmotors.net',
    '.freshmotors.net',  # Wildcard for all subdomains
]

# In DEBUG mode, also accept local network IPs (10.x.x.x, 192.168.x.x, etc.)
# This allows testing from phones and other devices on the same LAN.
if DEBUG:
    import socket
    try:
        hostname = socket.gethostname()
        local_ips = socket.getaddrinfo(hostname, None, socket.AF_INET)
        for _, _, _, _, addr in local_ips:
            if addr[0] not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(addr[0])
    except Exception:
        pass
    # Wildcard for any private network IP during development
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    # Daphne ASGI server — required for WebSocket support (Django Channels)
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'channels',  # WebSocket support
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT Authentication
    'rest_framework_simplejwt.token_blacklist',  # JWT blacklist for instant logout
    'corsheaders',  # CORS headers
    'axes',  # Brute-force login protection
    'news',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS - MUST be first!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'news.error_capture.ErrorCaptureMiddleware',  # Log all 500s to BackendErrorLog
    'news.bot_protection.BotProtectionMiddleware',  # Block bots — AFTER auth so we can skip authenticated users
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Brute-force protection — AFTER auth middleware
    'news.admin_2fa_middleware.Admin2FAMiddleware',  # 2FA for Django admin
    'news.middleware.MaintenanceModeMiddleware',  # Maintenance mode
]

ROOT_URLCONF = 'auto_news_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_news_site.wsgi.application'
ASGI_APPLICATION = 'auto_news_site.asgi.application'

# Channels (WebSocket) configuration
# Use Redis if available (production), fallback to InMemory (development)
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        },
    }

# Redis Cache Configuration
# Try to use Redis if available, fallback to dummy cache if not
try:
    import redis
    redis_client = redis.Redis.from_url(
        os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"), 
        socket_connect_timeout=1
    )
    redis_client.ping()  # Test connection
    
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "autonews",
            "TIMEOUT": 300,  # 5 minutes default
        }
    }
except (redis.ConnectionError, redis.RedisError, Exception):
    # Fallback to dummy cache if Redis is not available
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
    redis_client = None

# Session Configuration - Use Redis for faster sessions
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL and redis_client:
    # Store sessions in Redis (faster than database)
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    print("✓ Sessions stored in Redis")
else:
    # Fallback to database sessions
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Priority: DATABASE_URL (Railway) > individual env vars > defaults
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL (Railway provides this)
    import dj_database_url
    DATABASES = {
        # conn_max_age=0: close connections after each request
        # Prevents "too many clients" on Railway (limit ~25 connections)
        # conn_max_age=600 caused exhaustion when multiple workers kept connections open
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=0)
    }
else:
    # Fallback to individual environment variables (local development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'autonews'),
            'USER': os.getenv('POSTGRES_USER', 'autonews_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5433'),
            'CONN_MAX_AGE': 0,  # Always 0 — prevents 'too many clients' on Railway and local Docker PG
        }
    }

# SQLite configuration (для отката если нужно):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Date and time formatting
DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i:s'
SHORT_DATETIME_FORMAT = 'd.m.Y H:i'
USE_L10N = False


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_errors.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'ai_engine_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'ai_engine.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Set to DEBUG to see all SQL queries
            'propagate': False,
        },
        'ai_engine': {
            'handlers': ['console', 'ai_engine_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'news': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Create logs directory if it doesn't exist
import os
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # your-email@gmail.com
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # App Password from Google
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Fresh Motors <noreply@freshmotors.net>')
SERVER_EMAIL = EMAIL_HOST_USER

# Fallback to console email in development
if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary configuration for production (Railway has ephemeral filesystem)
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL')
if CLOUDINARY_URL:
    # Use Cloudinary for media storage (required for Railway - ephemeral filesystem!)
    # Insert at beginning of INSTALLED_APPS to ensure proper initialization
    if 'cloudinary_storage' not in INSTALLED_APPS:
        INSTALLED_APPS.insert(0, 'cloudinary_storage')
    if 'cloudinary' not in INSTALLED_APPS:
        INSTALLED_APPS.insert(1, 'cloudinary')
    
    # For Django 4.2+ use STORAGES, for older versions use DEFAULT_FILE_STORAGE
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    
    # Also set STORAGES for Django 4.2+
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    
    # Parse CLOUDINARY_URL into components
    # Format: cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    import re
    match = re.match(r'cloudinary://([^:]+):([^@]+)@(.+)', CLOUDINARY_URL)
    if match:
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': match.group(3),
            'API_KEY': match.group(1),
            'API_SECRET': match.group(2),
        }
        print(f"✓ Cloudinary configured: cloud={match.group(3)}")
    else:
        print(f"⚠️ Could not parse CLOUDINARY_URL: {CLOUDINARY_URL[:30]}...")
    
    print("✓ Cloudinary storage configured for media files")
else:
    print("⚠️ CLOUDINARY_URL not set - media files will use local storage (will be lost on redeploy!)")

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Fresh Motors Admin",
    "site_header": "Fresh Motors",
    "site_brand": "🚗 Fresh Motors",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "✅ You are logged in as:",
    "copyright": "Fresh Motors 2026",
    "search_model": ["news.Article", "news.Category"],
    "user_avatar": None,
    
    "topmenu_links": [
        {"name": "🏠 Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📰 View Site", "url": "/", "new_window": True},
        {"name": "➕ New Article", "url": "admin:news_article_add", "permissions": ["news.add_article"]},
    ],
    
    "usermenu_links": [
        {"name": "👤 My Profile", "url": "admin:auth_user_change", "new_window": False},
        {"name": "🔐 Change Password", "url": "admin:password_change", "new_window": False},
        {"model": "auth.user"}
    ],
    
    # Показывать имя пользователя в верхнем меню
    "show_ui_builder": False,
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["news", "auth"],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "news.Article": "fas fa-newspaper",
        "news.Category": "fas fa-folder",
        "news.Tag": "fas fa-tags",
        "news.CarSpecification": "fas fa-car",
        "news.SiteSettings": "fas fa-cog",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    "related_modal_active": False,
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'news.pagination.FlexiblePageNumberPagination',
    'PAGE_SIZE': 18,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/minute',   # Doubled: N+1 favorites/check was burning 20 req on one page load
        'user': '3000/hour'     # Tripled: admin dashboards load 5-10 endpoints per page
    }
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),   # 8h — comfortable admin session
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  # Rotate refresh tokens on use
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,  # Update last_login on token refresh
}

# CORS Settings - PRODUCTION SECURE
# Only allow requests from our own domains
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development, whitelist-only in production

# Allowed origins - only our domains
CORS_ALLOWED_ORIGINS = [
    # Production domains
    'https://freshmotors.net',
    'https://www.freshmotors.net',
    'https://api.freshmotors.net',
    # Railway deployments
    'https://autonews-ai-production.up.railway.app',
    'https://heroic-healing-production-2365.up.railway.app',
] + (
    # Local development (only if DEBUG=True)
    [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ] if DEBUG else []
)

# Also allow media files to be accessed cross-origin
CORS_URLS_REGEX = r'^.*$'  # Apply CORS to all URLs including /media/

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'sentry-trace',
    'baggage',
]

# CSRF Trusted Origins (required for Django 4.0+ cross-origin POST)
CSRF_TRUSTED_ORIGINS = [
    'https://freshmotors.net',
    'https://www.freshmotors.net',
    'https://api.freshmotors.net',
    'https://heroic-healing-production-2365.up.railway.app',
]

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Session Cookie Security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_NAME = 'sessionid'  # Don't reveal Django

# CSRF Cookie Security  
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
CSRF_COOKIE_SAMESITE = 'Lax'  # Additional protection
CSRF_COOKIE_NAME = 'csrftoken'  # Standard name

# HTTPS settings (activate in production)
if not DEBUG:
    # Railway proxy settings
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True  # HTTPS only
    CSRF_COOKIE_SECURE = True  # HTTPS only
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# File upload limits (Increased to 20MB for high-res press photos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB (previously 5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB (previously 5MB)

# Note: Sentry is already initialized at the top of this file (lines 24-33)
# Note: LOGGING is already configured above (lines 248-331) with file handlers and rotation


# ================================================
# SEO CONFIGURATION  
# ================================================

DEFAULT_SEO_TITLE = "FreshMotors - AI-Powered Automotive News & Reviews"
DEFAULT_SEO_DESCRIPTION = "Latest car reviews, automotive news, and vehicle comparisons powered by AI"
DEFAULT_SEO_KEYWORDS = "car reviews, automotive news, vehicle specs, car comparisons, electric vehicles"

# Site Settings
SITE_NAME = "FreshMotors"
SITE_DESCRIPTION = "AI-Powered Automotive News Platform"
CONTACT_EMAIL = "contact@freshmotors.com"


# ================================================
# RATE LIMITING CONFIGURATION
# ================================================

RATELIMIT_ENABLE = not DEBUG  # Disable in development, enable in production
RATELIMIT_USE_CACHE = 'default'

# ================================================
# DJANGO-AXES: Brute-Force Protection
# ================================================

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes must be first
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 0.5  # 30 minutes lockout (in hours)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # Don't lock whole IP behind NAT
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login
AXES_LOCKOUT_CALLABLE = None  # Use default 403 response
AXES_VERBOSE = DEBUG  # Log attempts only in debug mode
AXES_ENABLED = True  # Always enabled — lightweight and important

# ================================================
# WEBAUTHN / PASSKEY
# ================================================
# On Railway / production set these env vars:
#   WEBAUTHN_RP_ID            = freshmotors.net   (domain only, no https://)
#   WEBAUTHN_ALLOWED_ORIGINS  = https://www.freshmotors.net,https://freshmotors.net
#                               (comma-separated — supports www AND non-www)
#   WEBAUTHN_RP_NAME          = FreshMotors Admin  (display name)
# On localhost no env vars needed — defaults work fine.

WEBAUTHN_RP_ID = os.getenv('WEBAUTHN_RP_ID', 'localhost')
WEBAUTHN_ORIGIN = os.getenv('WEBAUTHN_ORIGIN', 'http://localhost:3000')   # legacy fallback
WEBAUTHN_ALLOWED_ORIGINS = os.getenv('WEBAUTHN_ALLOWED_ORIGINS', '')       # preferred: comma-separated list
WEBAUTHN_RP_NAME = os.getenv('WEBAUTHN_RP_NAME', 'FreshMotors Admin')

# ================================================
# TELEGRAM AUTO-PUBLISHING
# ================================================
# Bot token from @BotFather (FreshMotors Test_Bot1)
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
# Channel username (e.g. @freshmotors_news) or numeric chat_id
TELEGRAM_CHANNEL_ID = os.getenv('TELEGRAM_CHANNEL_ID', '@freshmotors_news')
# Admin user ID for error notifications
TELEGRAM_ADMIN_ID = os.getenv('TELEGRAM_ADMIN_ID', '496099589')
# Auto-post new articles to Telegram (set to 'true' to enable)
TELEGRAM_AUTO_POST = os.getenv('TELEGRAM_AUTO_POST', 'false').lower() == 'true'

# Site URL for article links in Telegram posts
SITE_URL = os.getenv('SITE_URL', 'https://www.freshmotors.net')

# ================================================
# CELERY CONFIGURATION
# ================================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Jerusalem'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # Hard limit: 30 min per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit: 25 min
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks to prevent memory leaks
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time (tasks are long-running)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Beat schedule — all periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # --- Fixed-interval tasks ---
    'gsc-sync-every-6h': {
        'task': 'news.tasks.gsc_sync',
        'schedule': crontab(minute=0, hour='*/6'),
    },
    'currency-update-daily': {
        'task': 'news.tasks.currency_update',
        'schedule': crontab(minute=30, hour=3),  # 3:30 AM Israel time
    },
    'scheduled-publish-every-minute': {
        'task': 'news.tasks.scheduled_publish',
        'schedule': crontab(minute='*'),  # Every minute
    },
    'deep-specs-backfill-every-6h': {
        'task': 'news.tasks.deep_specs_backfill',
        'schedule': crontab(minute=15, hour='*/6'),
    },
    'ab-lifecycle-daily': {
        'task': 'news.tasks.ab_lifecycle',
        'schedule': crontab(minute=0, hour=4),  # 4 AM Israel time
    },
    'stale-error-cleanup-every-6h': {
        'task': 'news.tasks.stale_error_cleanup',
        'schedule': crontab(minute=45, hour='*/6'),
    },
    # --- Dynamic-interval tasks (check settings each run) ---
    'rss-scan': {
        'task': 'news.tasks.rss_scan',
        'schedule': crontab(minute='*/30'),  # Check every 30 min, task itself checks settings
    },
    'youtube-scan': {
        'task': 'news.tasks.youtube_scan',
        'schedule': crontab(minute='*/30'),  # Check every 30 min, task itself checks settings
    },
    'auto-publish-check': {
        'task': 'news.tasks.auto_publish',
        'schedule': crontab(minute='*/10'),  # Every 10 min
    },
}

