# Generated by Django 6.0.1 on 2026-01-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_sitesettings'),
    ]

    operations = [
    ]
