# Generated by Django 6.0.1 on 2026-01-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional images for gallery', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption/description', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.article')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
