# Generated by Django 6.0.1 on 2026-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for AI generation'),
        ),
    ]
