# Generated by Django 6.0.1 on 2026-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this article has been viewed'),
        ),
    ]
