# Generated by Django 6.0.1 on 2026-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_enabled',
            field=models.BooleanField(default=False, help_text='Show Facebook link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_enabled',
            field=models.BooleanField(default=False, help_text='Show Instagram link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_enabled',
            field=models.BooleanField(default=False, help_text='Show LinkedIn link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Show Telegram link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_enabled',
            field=models.BooleanField(default=False, help_text='Show TikTok link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_enabled',
            field=models.BooleanField(default=False, help_text='Show Twitter/X link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_enabled',
            field=models.BooleanField(default=False, help_text='Show YouTube link'),
        ),
    ]
