# Generated by Django 4.2.16 on 2026-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_sitesettings_facebook_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of times this article has been viewed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin must approve'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at', 'is_published'], name='article_created_published_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-created_at'], name='article_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views'], name='article_views_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='news_catego_name_86e1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_approved', '-created_at'], name='news_commen_article_75454b_idx'),
        ),
    ]
