# Generated by Django 6.0.1 on 2026-01-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_options_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Screenshot 2 from video', null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Screenshot 3 from video', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Main featured image (screenshot 1)', null=True, upload_to='articles/'),
        ),
    ]
