# Generated by Django 6.0.1 on 2026-01-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_favorite'),
        ('news', '0012_article_image_2_article_image_3_alter_article_image'),
    ]

    operations = [
    ]
