# Generated by Django 6.0.1 on 2026-01-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_merge_20260120_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ip_address',
            field=models.CharField(help_text='User fingerprint (IP+UserAgent hash) for preventing multiple votes', max_length=255),
        ),
    ]
