# Generated by Django 4.2.16 on 2026-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_is_deleted_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_content',
            field=models.TextField(blank=True, help_text='HTML content for About page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_enabled',
            field=models.BooleanField(default=True, help_text='Show About page in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title',
            field=models.CharField(default='About AutoNews', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business inquiries email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Office address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_enabled',
            field=models.BooleanField(default=False, help_text='Show address in contacts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_enabled',
            field=models.BooleanField(default=True, help_text='Show Contact page in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle',
            field=models.CharField(blank=True, default="Have a question, suggestion, or just want to say hello? We'd love to hear from you!", max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title',
            field=models.CharField(default='Contact Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number to display', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_enabled',
            field=models.BooleanField(default=False, help_text='Show phone in contacts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page_content',
            field=models.TextField(blank=True, help_text='HTML content for Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page_enabled',
            field=models.BooleanField(default=True, help_text='Show Privacy Policy in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page_title',
            field=models.CharField(default='Privacy Policy', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_page_content',
            field=models.TextField(blank=True, help_text='HTML content for Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_page_enabled',
            field=models.BooleanField(default=True, help_text='Show Terms in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_page_title',
            field=models.CharField(default='Terms of Service', max_length=200),
        ),
    ]
