# Generated by Django 4.2.16 on 2026-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_add_page_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default="We're currently making improvements to bring you a better experience. Please check back soon!", help_text='Message shown to visitors during maintenance'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode - only admins can access the site'),
        ),
    ]
