# Generated by Django 4.2.16 on 2026-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_add_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (AI extracts from video)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='admin@freshmotors.net', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='© 2026 Fresh Motors. All rights reserved.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Fresh Motors', max_length=100),
        ),
    ]
