# Generated by Django 4.2.16 on 2026-01-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0021_add_user_to_comment_and_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_enabled', models.BooleanField(default=True, help_text='Receive weekly newsletter with top articles')),
                ('new_articles_enabled', models.BooleanField(default=False, help_text='Get notified when new articles are published')),
                ('comment_replies_enabled', models.BooleanField(default=True, help_text='Get notified when someone replies to your comment')),
                ('favorite_updates_enabled', models.BooleanField(default=False, help_text='Get notified about updates to your favorite articles')),
                ('marketing_enabled', models.BooleanField(default=False, help_text='Receive promotional emails and special offers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preferences',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
    ]
