# Generated by Django 6.0.1 on 2026-01-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default="We're currently performing maintenance to improve your experience. Please check back soon!", help_text='Message shown to visitors during maintenance', verbose_name='Maintenance Message'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode - only admins can access the site', verbose_name='Maintenance Mode'),
        ),
    ]
