# Generated by Django 6.0.1 on 2026-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_newsletterhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
    ]
