# Generated by Django 6.0.1 on 2026-01-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_article_meta_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('account_locked', 'Account Locked')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('old_value', models.CharField(blank=True, help_text='Old value (e.g., old email)', max_length=255)),
                ('new_value', models.CharField(blank=True, help_text='New value (e.g., new email)', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Additional details in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for failed login attempts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_securi_created_37f1b6_idx'), models.Index(fields=['user', '-created_at'], name='news_securi_user_id_ba9933_idx'), models.Index(fields=['action', '-created_at'], name='news_securi_action_b4bbb2_idx')],
            },
        ),
    ]
