# Generated by Django 6.0.1 on 2026-01-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_emailverification_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingarticle',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Car specifications (Make, Model, Year, etc.)'),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Suggested tags list'),
        ),
    ]
