# Generated by Django 6.0.1 on 2026-01-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_pendingarticle_specs_pendingarticle_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Tag Group',
                'verbose_name_plural': 'Tag Groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Category group for this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='news.taggroup'),
        ),
    ]
