# Generated by Django 6.0.1 on 2026-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_taggroup_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hero',
            field=models.BooleanField(db_index=True, default=False, help_text='Show in Home page Hero section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Your premier source for automotive news, reviews, and insights', help_text='Custom subtitle for Hero section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Welcome to Fresh Motors', help_text='Custom title for Hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='use_classic_hero',
            field=models.BooleanField(default=False, help_text='Show classic purple background instead of dynamic articles'),
        ),
    ]
