# Generated by Django 6.0.1 on 2026-02-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_article_is_hero_sitesettings_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GSC Daily Report',
                'verbose_name_plural': 'GSC Daily Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleGSCStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('top_queries', models.JSONField(blank=True, default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_stats', to='news.article')),
            ],
            options={
                'verbose_name': 'Article Search Stat',
                'verbose_name_plural': 'Article Search Stats',
                'ordering': ['-date'],
                'unique_together': {('article', 'date')},
            },
        ),
    ]
