# Generated by Django 6.0.1 on 2026-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_gscreport_articlegscstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Main featured image (screenshot 1)', max_length=255, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Screenshot 2 from video', max_length=255, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Screenshot 3 from video', max_length=255, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(help_text='Additional images for gallery', max_length=255, upload_to='gallery/'),
        ),
    ]
