# Generated by Django 6.0.1 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_alter_article_image_alter_article_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='make',
            field=models.CharField(blank=True, help_text='Car Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='model',
            field=models.CharField(blank=True, help_text='Base Model', max_length=100),
        ),
        migrations.AddField(
            model_name='carspecification',
            name='trim',
            field=models.CharField(blank=True, help_text='Trim or Version', max_length=100),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='model_name',
            field=models.CharField(help_text='Specific trim or model (Legacy)', max_length=200),
        ),
    ]
