# Generated by Django 6.0.1 on 2026-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_channel_url',
            field=models.URLField(blank=True, help_text='Original creator channel URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, help_text='Original content creator name', max_length=200),
        ),
    ]
