# Generated by Django 6.0.1 on 2026-02-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_article_author_channel_url_article_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingarticle',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original article/press release URL'),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='video_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='video_url',
            field=models.URLField(blank=True, help_text='Source YouTube video URL'),
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Feed name for display (e.g., 'Mercedes-Benz Press')", max_length=200)),
                ('feed_url', models.URLField(help_text='RSS/Atom feed URL', unique=True)),
                ('website_url', models.URLField(blank=True, help_text='Main website URL')),
                ('source_type', models.CharField(choices=[('brand', 'Automotive Brand'), ('media', 'Automotive Media'), ('blog', 'Industry Blog')], default='brand', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable monitoring for this feed')),
                ('auto_publish', models.BooleanField(default=False, help_text='Automatically publish articles (skip review)')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_entry_date', models.DateTimeField(blank=True, help_text='Publication date of last processed entry', null=True)),
                ('entries_processed', models.IntegerField(default=0)),
                ('logo_url', models.URLField(blank=True, help_text='Brand/source logo URL')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, help_text='Default category for articles from this feed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='rss_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_articles', to='news.rssfeed'),
        ),
    ]
