# Generated by Django 6.0.1 on 2026-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_pendingarticle_content_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='article_category_created_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.category'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
