# Generated by Django 6.0.1 on 2026-02-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_vehiclespecs'),
        ('news', '0038_vehiclespecs_and_more'),
    ]

    operations = [
    ]
