# Generated by Django 6.0.1 on 2026-02-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_vehiclespecs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(help_text='768-dimensional embedding vector from Gemini (stored as JSON array)')),
                ('model_name', models.CharField(default='models/embedding-001', help_text='Gemini model used to generate this embedding', max_length=100)),
                ('text_hash', models.CharField(blank=True, help_text='SHA256 hash of indexed text (to detect changes)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='Article this embedding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='news.article')),
            ],
            options={
                'verbose_name': 'Article Embedding',
                'verbose_name_plural': 'Article Embeddings',
                'db_table': 'article_embeddings',
                'indexes': [models.Index(fields=['article'], name='article_emb_article_8fbb22_idx'), models.Index(fields=['updated_at'], name='article_emb_updated_78b8b7_idx'), models.Index(fields=['text_hash'], name='article_emb_text_ha_a4d8fa_idx')],
            },
        ),
    ]
