# Generated by Django 6.0.1 on 2026-02-13 10:21
# Modified to safely handle existing table

import django.db.models.deletion
from django.db import migrations, models, connection


def create_rssnewsitem_if_not_exists(apps, schema_editor):
    """Safely create RSSNewsItem table only if it doesn't exist."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'news_rssnewsitem'
            );
        """)
        table_exists = cursor.fetchone()[0]

        if table_exists:
            print("Table 'news_rssnewsitem' already exists, skipping creation")
            return

        print("Creating table 'news_rssnewsitem'...")
        cursor.execute("""
            CREATE TABLE "news_rssnewsitem" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "title" varchar(500) NOT NULL,
                "content" text NOT NULL DEFAULT '',
                "excerpt" text NOT NULL DEFAULT '',
                "source_url" varchar(200) NOT NULL DEFAULT '',
                "image_url" varchar(1000) NOT NULL DEFAULT '',
                "content_hash" varchar(64) NOT NULL DEFAULT '',
                "published_at" timestamp with time zone NULL,
                "status" varchar(20) NOT NULL DEFAULT 'new',
                "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "pending_article_id" bigint NULL REFERENCES "news_pendingarticle" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                "rss_feed_id" bigint NOT NULL REFERENCES "news_rssfeed" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
        """)
        cursor.execute('CREATE INDEX "news_rssnew_content_0d6e7f_idx" ON "news_rssnewsitem" ("content_hash");')
        cursor.execute('CREATE INDEX "news_rssnew_status_b79bff_idx" ON "news_rssnewsitem" ("status", "created_at" DESC);')
        cursor.execute('CREATE INDEX "news_rssnew_rss_fee_bc6b51_idx" ON "news_rssnewsitem" ("rss_feed_id", "created_at" DESC);')
        print("Table 'news_rssnewsitem' created successfully")


def reverse_rssnewsitem(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "news_rssnewsitem" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_increase_article_title_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleembedding',
            name='model_name',
            field=models.CharField(default='models/gemini-embedding-001', help_text='Gemini model used to generate this embedding', max_length=100),
        ),
        migrations.RunPython(create_rssnewsitem_if_not_exists, reverse_rssnewsitem),
    ]
