# Generated by Django 6.0.1 on 2026-02-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_increase_article_title_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleembedding',
            name='model_name',
            field=models.CharField(default='models/gemini-embedding-001', help_text='Gemini model used to generate this embedding', max_length=100),
        ),
        migrations.CreateModel(
            name='RSSNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, help_text='Raw HTML content from RSS')),
                ('excerpt', models.TextField(blank=True, help_text='Plain text snippet for preview')),
                ('source_url', models.URLField(blank=True, help_text='Link to original article')),
                ('image_url', models.URLField(blank=True, help_text='Featured image URL', max_length=1000)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash for deduplication', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, help_text='Original publication date', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('generating', 'Generating Article'), ('generated', 'Article Generated'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_news_item', to='news.pendingarticle')),
                ('rss_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='news.rssfeed')),
            ],
            options={
                'verbose_name': 'RSS News Item',
                'verbose_name_plural': 'RSS News Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='news_rssnew_status_b79bff_idx'), models.Index(fields=['rss_feed', '-created_at'], name='news_rssnew_rss_fee_bc6b51_idx')],
            },
        ),
    ]
