# Generated by Django 6.0.1 on 2026-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0051_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_original',
            field=models.TextField(blank=True, help_text='Original AI-generated content (before manual edits). Used for AI quality metrics.'),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('SUV', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('crossover', 'Crossover'), ('wagon', 'Wagon'), ('shooting_brake', 'Shooting Brake'), ('van', 'Van'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('liftback', 'Liftback'), ('fastback', 'Fastback'), ('MPV', 'MPV / Minivan'), ('roadster', 'Roadster'), ('cabriolet', 'Cabriolet'), ('targa', 'Targa'), ('limousine', 'Limousine')], help_text='Body style', max_length=20, null=True),
        ),
    ]

