# Generated by Django 6.0.1 on 2026-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0052_add_content_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='generation_metadata',
            field=models.JSONField(blank=True, help_text='AI generation stats: timing, provider, AI Editor diff', null=True),
        ),
    ]

