# Generated by Django 6.0.1 on 2026-02-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_add_generation_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('factual_error', 'Factual Error'), ('typo', 'Typo / Grammar'), ('outdated', 'Outdated Information'), ('hallucination', 'AI Hallucination'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField(help_text="User's description of the issue", max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='news.article')),
            ],
            options={
                'verbose_name': 'Article Feedback',
                'verbose_name_plural': 'Article Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
