# Generated by Django 6.0.1 on 2026-02-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0055_article_title_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclespecs",
            name="combined_range_km",
            field=models.IntegerField(blank=True, help_text="Total combined range for PHEVs (gas+electric) in km", null=True),
        ),
        migrations.AddField(
            model_name="vehiclespecs",
            name="price_updated_at",
            field=models.DateTimeField(blank=True, help_text="When price/exchange rate was last updated", null=True),
        ),
        migrations.AddField(
            model_name="vehiclespecs",
            name="price_usd_from",
            field=models.IntegerField(blank=True, help_text="Price in USD (auto-converted from original currency)", null=True),
        ),
        migrations.AddField(
            model_name="vehiclespecs",
            name="price_usd_to",
            field=models.IntegerField(blank=True, help_text="Max price in USD (auto-converted)", null=True),
        ),
    ]
