# Generated by Django 6.0.1 on 2026-02-18 06:02
# Fixed: Table already exists (created by migration 0043 via RunSQL).
# Using SeparateDatabaseAndState to register the model in Django migration
# state without trying to create the table again.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0056_add_combined_range_and_usd_prices"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # No database operation - table already exists from migration 0043
            database_operations=[],
            # State operation - register the model so Django knows about it
            state_operations=[
                migrations.CreateModel(
                    name="RSSNewsItem",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(max_length=500)),
                        ("content", models.TextField(blank=True, help_text="Raw HTML content from RSS")),
                        ("excerpt", models.TextField(blank=True, help_text="Plain text snippet for preview")),
                        ("source_url", models.URLField(blank=True, help_text="Link to original article")),
                        ("image_url", models.URLField(blank=True, help_text="Featured image URL", max_length=1000)),
                        ("content_hash", models.CharField(blank=True, db_index=True, help_text="SHA256 hash for deduplication", max_length=64)),
                        ("published_at", models.DateTimeField(blank=True, help_text="Original publication date", null=True)),
                        ("status", models.CharField(choices=[("new", "New"), ("read", "Read"), ("generating", "Generating Article"), ("generated", "Article Generated"), ("dismissed", "Dismissed")], default="new", max_length=20)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("pending_article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_news_item", to="news.pendingarticle")),
                        ("rss_feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="news_items", to="news.rssfeed")),
                    ],
                    options={
                        "verbose_name": "RSS News Item",
                        "verbose_name_plural": "RSS News Items",
                        "ordering": ["-created_at"],
                        "indexes": [
                            models.Index(fields=["status", "-created_at"], name="news_rssnew_status_b79bff_idx"),
                            models.Index(fields=["rss_feed", "-created_at"], name="news_rssnew_rss_fee_bc6b51_idx"),
                        ],
                    },
                ),
            ],
        ),
    ]
