# Generated by Django 6.0.1 on 2026-02-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0057_fix_rssnewsitem_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleembedding',
            name='article_emb_updated_78b8b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='articleembedding',
            name='article_emb_text_ha_a4d8fa_idx',
        ),
    ]
