# Generated by Django 6.0.1 on 2026-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0058_remove_unused_embedding_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_price',
            field=models.BooleanField(default=True, help_text='Show price on public page'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_source',
            field=models.BooleanField(default=True, help_text='Show source/author credit on public page'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_youtube',
            field=models.BooleanField(default=True, help_text='Show YouTube video embed on public page'),
        ),
    ]
