# Generated by Django 6.0.1 on 2026-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0059_add_visibility_toggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this ad placement', max_length=200)),
                ('position', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar'), ('between_articles', 'Between Articles (List)'), ('after_content', 'After Article Content'), ('footer', 'Footer')], db_index=True, max_length=30)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner (Image + Link)'), ('html_code', 'HTML/JS Code (AdSense, etc)'), ('sponsored', 'Sponsored Content (Text + Image)')], default='banner', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='ads/')),
                ('link', models.URLField(blank=True, help_text='Click-through URL', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Image alt text', max_length=200)),
                ('html_code', models.TextField(blank=True, help_text='Raw HTML/JS code to embed')),
                ('sponsor_name', models.CharField(blank=True, help_text='Sponsor/advertiser name', max_length=200)),
                ('sponsor_text', models.TextField(blank=True, help_text='Sponsored message text')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable this ad')),
                ('start_date', models.DateTimeField(blank=True, help_text='Start showing (empty = immediately)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Stop showing (empty = forever)', null=True)),
                ('duration_preset', models.CharField(blank=True, default='unlimited', help_text='Duration preset used when creating', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher = shown first')),
                ('target_pages', models.CharField(blank=True, default='all', help_text='Where to show: all, articles, home, cars', max_length=200)),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Times displayed')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Times clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
