# Generated by Django 6.0.1 on 2026-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0060_add_ad_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_scan_enabled', models.BooleanField(default=False, help_text='Enable automatic RSS feed scanning')),
                ('rss_scan_interval_minutes', models.IntegerField(default=30, help_text='Minutes between RSS scans (15, 30, 60, 120)')),
                ('rss_max_articles_per_scan', models.IntegerField(default=10, help_text='Max articles to process per scan cycle')),
                ('rss_last_run', models.DateTimeField(blank=True, help_text='When RSS scan last ran', null=True)),
                ('rss_last_status', models.CharField(blank=True, default='', help_text='Last scan result message', max_length=500)),
                ('rss_articles_today', models.IntegerField(default=0)),
                ('youtube_scan_enabled', models.BooleanField(default=False, help_text='Enable automatic YouTube channel scanning')),
                ('youtube_scan_interval_minutes', models.IntegerField(default=120, help_text='Minutes between YouTube scans (60, 120, 240)')),
                ('youtube_max_videos_per_scan', models.IntegerField(default=3, help_text='Max videos to process per scan cycle')),
                ('youtube_last_run', models.DateTimeField(blank=True, help_text='When YouTube scan last ran', null=True)),
                ('youtube_last_status', models.CharField(blank=True, default='', help_text='Last scan result message', max_length=500)),
                ('youtube_articles_today', models.IntegerField(default=0)),
                ('auto_publish_enabled', models.BooleanField(default=False, help_text='Enable automatic publishing of high-quality pending articles')),
                ('auto_publish_min_quality', models.IntegerField(default=7, help_text='Minimum quality score (1-10) required for auto-publish')),
                ('auto_publish_max_per_hour', models.IntegerField(default=3, help_text='Maximum articles to auto-publish per hour')),
                ('auto_publish_max_per_day', models.IntegerField(default=20, help_text='Maximum articles to auto-publish per day')),
                ('auto_publish_require_image', models.BooleanField(default=True, help_text='Require featured image before auto-publishing')),
                ('auto_publish_today_count', models.IntegerField(default=0, help_text='Counter: articles auto-published today')),
                ('auto_publish_today_date', models.DateField(blank=True, help_text="Date for today's counter", null=True)),
                ('auto_publish_last_run', models.DateTimeField(blank=True, help_text='When auto-publish last checked', null=True)),
                ('google_indexing_enabled', models.BooleanField(default=True, help_text='Auto-submit published articles to Google Indexing API')),
                ('counters_reset_date', models.DateField(blank=True, help_text='Last date counters were reset', null=True)),
            ],
            options={
                'verbose_name': 'Automation Settings',
                'verbose_name_plural': 'Automation Settings',
            },
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='Auto-assessed quality 1-10 (used for auto-publish threshold)'),
        ),
    ]
