# Generated by Django 6.0.1 on 2026-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0061_add_automation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_image_mode',
            field=models.CharField(choices=[('off', 'Off — no auto image'), ('search_first', 'Search first → AI fallback'), ('search_only', 'Search only — no AI'), ('ai_only', 'AI only — generate from reference')], default='off', help_text='How to auto-attach images to published articles', max_length=20),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_image_prefer_press',
            field=models.BooleanField(default=True, help_text='Prefer editorial/press photos (green-highlighted) over others'),
        ),
    ]
