# Generated by Django 6.0.1 on 2026-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0062_add_auto_image_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationsettings',
            name='auto_publish_today_date',
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_image_last_run',
            field=models.DateTimeField(blank=True, help_text='When auto-image last ran', null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_image_last_status',
            field=models.CharField(blank=True, default='', help_text='Last auto-image result', max_length=500),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_image_today_count',
            field=models.IntegerField(default=0, help_text='Images generated today'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='google_indexing_last_run',
            field=models.DateTimeField(blank=True, help_text='When Google Indexing last submitted', null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='google_indexing_last_status',
            field=models.CharField(blank=True, default='', help_text='Last indexing result', max_length=500),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='google_indexing_today_count',
            field=models.IntegerField(default=0, help_text='Articles indexed today'),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='is_auto_published',
            field=models.BooleanField(default=False, help_text='Was this article auto-published (vs manually reviewed)'),
        ),
        migrations.AlterField(
            model_name='automationsettings',
            name='auto_image_mode',
            field=models.CharField(choices=[('off', 'Off — no auto image'), ('search_first', 'Find reference → AI generate')], default='off', help_text='Find a reference photo online, then generate AI image from it', max_length=20),
        ),
    ]
