# Generated by Django 6.0.1 on 2026-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0063_remove_automationsettings_auto_publish_today_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_publish_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_publish_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='rss_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='rss_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='score_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='score_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='youtube_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='youtube_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
