# Generated by Django 6.0.1 on 2026-02-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0064_automationsettings_auto_publish_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='license_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='license_details',
            field=models.TextField(blank=True, help_text="AI analysis of the site's content licensing terms"),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='license_status',
            field=models.CharField(choices=[('unchecked', 'Not Checked'), ('green', 'Free to Use'), ('yellow', 'Use with Caution'), ('red', 'Restricted')], default='unchecked', help_text='Content license status based on robots.txt and Terms of Use analysis', max_length=20),
        ),
    ]
