# Generated by Django 6.0.1 on 2026-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0065_rssfeed_license_checked_at_rssfeed_license_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='image_policy',
            field=models.CharField(choices=[('original', 'Use Original Images'), ('pexels_only', 'Use Pexels Only'), ('pexels_fallback', 'Original + Pexels Fallback')], default='pexels_fallback', help_text='How to source images: original (press), pexels_only (media), or fallback', max_length=20),
        ),
    ]
