# Generated by Django 6.0.1 on 2026-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0066_rssfeed_image_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='safety_checks',
            field=models.JSONField(blank=True, default=dict, help_text='Step-by-step safety evaluation: robots_txt, press_portal, tos_analysis, image_rights'),
        ),
    ]
