# Generated by Django 6.0.1 on 2026-02-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0067_add_safety_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_publish_require_safe_feed',
            field=models.BooleanField(default=True, help_text="Only auto-publish articles from feeds with safety_score != 'unsafe'"),
        ),
        migrations.CreateModel(
            name='AutoPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('published', 'Published'), ('skipped_quality', 'Skipped: Low Quality'), ('skipped_safety', 'Skipped: Feed Unsafe'), ('skipped_no_image', 'Skipped: No Image'), ('skipped_limit', 'Skipped: Rate Limit'), ('failed', 'Failed: Error')], max_length=30)),
                ('reason', models.TextField(help_text='Human-readable explanation')),
                ('quality_score', models.IntegerField(default=0)),
                ('safety_score', models.CharField(blank=True, default='', max_length=20)),
                ('image_policy', models.CharField(blank=True, default='', max_length=20)),
                ('feed_name', models.CharField(blank=True, default='', max_length=300)),
                ('source_type', models.CharField(blank=True, default='', max_length=20)),
                ('article_title', models.CharField(blank=True, default='', max_length=500)),
                ('content_length', models.IntegerField(default=0, help_text='Article content length in chars')),
                ('has_image', models.BooleanField(default=False)),
                ('has_specs', models.BooleanField(default=False)),
                ('tag_count', models.IntegerField(default=0)),
                ('category_name', models.CharField(blank=True, default='', max_length=100)),
                ('source_is_youtube', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_logs', to='news.pendingarticle')),
                ('published_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_logs', to='news.article')),
            ],
            options={
                'verbose_name': 'Auto-Publish Log',
                'verbose_name_plural': 'Auto-Publish Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_autopu_created_edaa72_idx'), models.Index(fields=['decision'], name='news_autopu_decisio_8660ee_idx')],
            },
        ),
    ]
