# Generated by Django 6.0.1 on 2026-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0068_add_auto_publish_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletitlevariant',
            name='auto_pick_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Minimum impressions per variant before auto-picking winner'),
        ),
        migrations.AddField(
            model_name='articletitlevariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this test still running?'),
        ),
    ]
