# Generated by Django 6.0.1 on 2026-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0070_add_unique_video_id_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoPublishSchedule',
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='site_theme',
            field=models.CharField(choices=[('default', 'Default (Indigo/Purple)'), ('midnight-green', 'Midnight Green (Emerald)'), ('deep-ocean', 'Deep Ocean (Blue)')], default='default', help_text='Site-wide color theme', max_length=30),
        ),
    ]
