# Generated by Django 6.0.1 on 2026-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0071_add_site_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingarticle',
            name='auto_publish_attempts',
            field=models.IntegerField(default=0, help_text='Number of auto-publish attempts'),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='auto_publish_last_attempt',
            field=models.DateTimeField(blank=True, help_text='When last auto-publish was attempted', null=True),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='auto_publish_last_error',
            field=models.TextField(blank=True, help_text='Last auto-publish error for debugging'),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('auto_failed', 'Auto-Publish Failed')], default='pending', max_length=20),
        ),
    ]
