# Generated by Django 6.0.1 on 2026-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0072_circuit_breaker_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_publish_as_draft',
            field=models.BooleanField(default=True, help_text='Create articles as drafts (requires manual approval) instead of publishing directly'),
        ),
        migrations.AddField(
            model_name='autopublishlog',
            name='review_time_seconds',
            field=models.IntegerField(blank=True, help_text='How long the human spent reviewing (seconds) — faster = more confident', null=True),
        ),
        migrations.AddField(
            model_name='autopublishlog',
            name='reviewer_notes',
            field=models.TextField(blank=True, default='', help_text='Why the reviewer approved/rejected — ML training data'),
        ),
        migrations.AlterField(
            model_name='autopublishlog',
            name='decision',
            field=models.CharField(choices=[('published', 'Published'), ('drafted', 'Drafted (Awaiting Review)'), ('human_approved', 'Human Approved'), ('human_rejected', 'Human Rejected'), ('skipped_quality', 'Skipped: Low Quality'), ('skipped_safety', 'Skipped: Feed Unsafe'), ('skipped_no_image', 'Skipped: No Image'), ('skipped_limit', 'Skipped: Rate Limit'), ('failed', 'Failed: Error')], max_length=30),
        ),
    ]
