# Generated by Django 6.0.1 on 2026-02-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0073_draft_toggle_and_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_keywords', models.JSONField(default=list, help_text='Extracted keywords from title (lowercase)')),
                ('final_tags', models.JSONField(default=list, help_text='Tag names the user approved for this article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_learning_log', to='news.article')),
            ],
            options={
                'verbose_name': 'Tag Learning Log',
                'verbose_name_plural': 'Tag Learning Logs',
                'indexes': [models.Index(fields=['-updated_at'], name='news_taglea_updated_77750c_idx')],
            },
        ),
    ]
