# Generated by Django 6.0.1 on 2026-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0077_theme_analytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commentmoderationlog',
            new_name='news_commen_decisio_e2c3b1_idx',
            old_name='news_commen_decisio_idx',
        ),
        migrations.RenameIndex(
            model_name='themeanalytics',
            new_name='news_themea_theme_3af109_idx',
            old_name='news_themea_theme_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='image_source',
            field=models.CharField(choices=[('youtube', 'YouTube Thumbnail'), ('rss_original', 'RSS / Press Release Original'), ('pexels', 'Pexels Stock Photo'), ('uploaded', 'Manual Upload'), ('unknown', 'Unknown')], default='unknown', help_text='Where the article images came from (youtube, rss_original, pexels, uploaded)', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingarticle',
            name='image_source',
            field=models.CharField(choices=[('youtube', 'YouTube Thumbnail'), ('rss_original', 'RSS / Press Release Original'), ('pexels', 'Pexels Stock Photo'), ('uploaded', 'Manual Upload'), ('unknown', 'Unknown')], default='unknown', help_text='Where the images came from (youtube, rss_original, pexels, uploaded)', max_length=20),
        ),
    ]
