# Generated by Django 6.0.1 on 2026-02-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0078_add_image_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reformat', '✨ Reformat with AI'), ('re_enrich', '⚡ Re-enrich Specs'), ('regenerate', '🔄 Regenerate'), ('edit_save', '💾 Article Saved'), ('image_change', '🖼️ Image Changed'), ('publish', '📢 Published'), ('unpublish', '📝 Unpublished')], db_index=True, max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, help_text='Action-specific data: lengths, field changes, provider info, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to='news.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='news_admina_action_418098_idx'), models.Index(fields=['article', '-created_at'], name='news_admina_article_1d5785_idx')],
            },
        ),
    ]
