# Generated by Django 6.0.1 on 2026-02-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0080_pendingarticle_author_channel_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dwell_time_seconds', models.PositiveIntegerField(default=0, help_text='Total active seconds spent on the article')),
                ('max_scroll_depth_pct', models.PositiveIntegerField(default=0, help_text='Maximum scroll depth reached (0-100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_metrics', to='news.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read Metric',
                'verbose_name_plural': 'Read Metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='news_readme_article_7b4f94_idx')],
            },
        ),
    ]
