# Generated by Django 6.0.1 on 2026-02-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0081_readmetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_url', models.CharField(max_length=500)),
                ('link_type', models.CharField(choices=[('ai_inline', 'AI Contextual Inline Link'), ('ai_read_also', 'AI Read Also Block'), ('related_carousel', 'Related Articles Carousel'), ('other', 'Other Internal Link')], default='other', max_length=20)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_clicks', to='news.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Link Click',
                'verbose_name_plural': 'Internal Link Clicks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_article', 'link_type', '-created_at'], name='news_intern_source__c33c37_idx')],
            },
        ),
    ]
