# Generated by Django 6.0.1 on 2026-02-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0082_internallinkclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('A', 'Variant A (Original)'), ('B', 'Variant B'), ('C', 'Variant C')], max_length=1)),
                ('image_url', models.CharField(help_text='URL or Cloudinary path to the image', max_length=1000)),
                ('image_source', models.CharField(choices=[('youtube', 'YouTube Thumbnail'), ('rss_original', 'Original Source'), ('pexels', 'Pexels'), ('ai_generated', 'AI Generated'), ('uploaded', 'Manual Upload'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Number of times shown')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of click-throughs')),
                ('is_winner', models.BooleanField(default=False, help_text='Winning variant (applied as main image)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this test still running?')),
                ('auto_pick_threshold', models.PositiveIntegerField(default=500, help_text='Minimum impressions per variant before auto-picking winner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_variants', to='news.article')),
            ],
            options={
                'verbose_name': 'Image A/B Variant',
                'verbose_name_plural': 'Image A/B Variants',
                'ordering': ['variant'],
                'unique_together': {('article', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='ArticleMicroFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('component_type', models.CharField(help_text='e.g. vehicle_specs, fact_block, pros_cons', max_length=50)),
                ('is_helpful', models.BooleanField(help_text='True for 👍, False for 👎')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_feedback', to='news.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Micro-Feedback',
                'verbose_name_plural': 'Article Micro-Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'component_type'], name='news_articl_article_7645a0_idx'), models.Index(fields=['component_type', 'is_helpful'], name='news_articl_compone_4a0b69_idx')],
            },
        ),
    ]
