# Generated by Django 6.0.1 on 2026-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0083_articleimagevariant_articlemicrofeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('js_error', 'JavaScript Reference Error'), ('network', 'Network / API Failure'), ('hydration', 'React Hydration Mismatch'), ('resource_404', 'Missing Resource (404)'), ('performance', 'Performance Violation'), ('other', 'Other')], default='other', max_length=50)),
                ('message', models.TextField(help_text='Primary error message')),
                ('stack_trace', models.TextField(blank=True, help_text='Component stack or JS stack trace')),
                ('url', models.URLField(help_text='Page URL where the error occurred', max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this similar error was caught')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Frontend Event Log',
                'verbose_name_plural': 'Frontend Event Logs',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='news_fronte_last_se_3177c6_idx'), models.Index(fields=['resolved'], name='news_fronte_resolve_2ac879_idx'), models.Index(fields=['error_type'], name='news_fronte_error_t_035736_idx')],
            },
        ),
    ]
