# Generated by Django 6.0.1 on 2026-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0084_frontendeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('page_leave', 'Page Leave (dwell + scroll)'), ('card_click', 'Article Card Click'), ('search', 'Search Query'), ('filter_use', 'Filter Applied'), ('recommended_impression', 'Recommended Section Shown'), ('recommended_click', 'Recommended Article Clicked'), ('compare_use', 'Compare Tool Used'), ('infinite_scroll', 'Infinite Scroll Load'), ('ad_impression', 'Ad Banner Shown'), ('ad_click', 'Ad Banner Clicked')], db_index=True, max_length=30)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('articles', 'Articles Listing'), ('article_detail', 'Article Detail'), ('trending', 'Trending Page'), ('cars', 'Cars Listing'), ('car_detail', 'Car Detail'), ('compare', 'Compare Page'), ('categories', 'Categories Page'), ('category_detail', 'Category Detail'), ('other', 'Other')], default='other', max_length=30)),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('referrer_page', models.CharField(blank=True, default='', help_text='Internal referrer: home, articles, recommended, search, direct', max_length=200)),
                ('device_type', models.CharField(blank=True, default='', help_text='desktop, tablet, mobile', max_length=10)),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_hash', models.CharField(blank=True, default='', help_text='Anonymized session fingerprint', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page Analytics Event',
                'verbose_name_plural': 'Page Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='news_pagean_event_t_2049fe_idx'), models.Index(fields=['page_type', '-created_at'], name='news_pagean_page_ty_31876d_idx'), models.Index(fields=['session_hash', '-created_at'], name='news_pagean_session_2115bf_idx')],
            },
        ),
    ]
