# Generated by Django 6.0.1 on 2026-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0085_page_analytics_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Reader engagement score (0-10). Computed from scroll depth, dwell time, ratings, comments.'),
        ),
        migrations.AddField(
            model_name='article',
            name='engagement_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the engagement score was last recalculated', null=True),
        ),
    ]
