# Generated by Django 6.0.1 on 2026-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0086_engagement_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_channel_url',
            field=models.URLField(blank=True, help_text='Original creator channel URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for AI generation', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='author_channel_url',
            field=models.URLField(blank=True, help_text='Original creator channel URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='featured_image',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original article/press release URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='video_url',
            field=models.URLField(blank=True, help_text='Source YouTube video URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='feed_url',
            field=models.URLField(help_text='RSS/Atom feed URL', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Brand/source logo URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='website_url',
            field=models.URLField(blank=True, help_text='Main website URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='rssnewsitem',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to original article', max_length=2000),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_url',
            field=models.URLField(help_text='YouTube channel URL (e.g., https://www.youtube.com/@ChannelName)', max_length=2000),
        ),
    ]
