# Generated by Django 6.0.1 on 2026-02-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0087_increase_url_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API Request (500)'), ('scheduler', 'Scheduler Task'), ('middleware', 'Middleware')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=10)),
                ('error_class', models.CharField(help_text='Exception class name, e.g. ValueError', max_length=255)),
                ('message', models.TextField(help_text='Error message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback')),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('request_user', models.CharField(blank=True, default='', max_length=150)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('task_name', models.CharField(blank=True, default='', help_text='Scheduler task name, e.g. rss_scan, youtube_scan', max_length=100)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Backend Error Log',
                'verbose_name_plural': 'Backend Error Logs',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='news_backen_last_se_953af1_idx'), models.Index(fields=['resolved'], name='news_backen_resolve_71708b_idx'), models.Index(fields=['source', '-last_seen'], name='news_backen_source_04ff94_idx'), models.Index(fields=['severity', '-last_seen'], name='news_backen_severit_493f9a_idx')],
            },
        ),
    ]
