# Generated by Django 6.0.1 on 2026-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0088_add_backend_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandalias',
            name='model_prefix',
            field=models.CharField(blank=True, default='', help_text='Sub-brand prefix in model name. If set, only matches when model starts with this prefix. Prefix is stripped from model.', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandalias',
            name='alias',
            field=models.CharField(help_text="The name variation (what AI might produce, e.g. 'DongFeng VOYAH')", max_length=100),
        ),
        migrations.AlterField(
            model_name='frontendeventlog',
            name='error_type',
            field=models.CharField(choices=[('js_error', 'JavaScript Error'), ('network', 'Network / API Failure'), ('hydration', 'React Hydration Mismatch'), ('resource_404', 'Missing Resource (404)'), ('performance', 'Performance Violation'), ('react_crash', 'React Component Crash'), ('api_4xx', 'API Client Error (4xx)'), ('api_5xx', 'API Server Error (5xx)'), ('unhandled_rejection', 'Unhandled Promise Rejection'), ('caught_error', 'Caught Error (try/catch)'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='brandalias',
            constraint=models.UniqueConstraint(fields=('alias', 'model_prefix'), name='unique_alias_prefix'),
        ),
    ]
