# Generated by Django 6.0.1 on 2026-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0089_brandalias_model_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecification',
            name='is_make_locked',
            field=models.BooleanField(default=False, help_text="When True, make/model won't be overwritten by AI re-extraction or VehicleSpecs sync. Set automatically by move-article."),
        ),
    ]
