# Generated by Django 6.0.1 on 2026-03-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0090_carspec_is_make_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_source',
            field=models.CharField(choices=[('youtube', 'YouTube Thumbnail'), ('rss_original', 'RSS / Press Release Original'), ('pexels', 'Pexels Stock Photo'), ('web_search', 'Web Search Photo'), ('ai_generated', 'AI Generated'), ('uploaded', 'Manual Upload'), ('unknown', 'Unknown')], default='unknown', help_text='Where the article images came from (youtube, rss_original, pexels, uploaded)', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='image_source',
            field=models.CharField(choices=[('youtube', 'YouTube Thumbnail'), ('rss_original', 'RSS / Press Release Original'), ('pexels', 'Pexels Stock Photo'), ('web_search', 'Web Search Photo'), ('ai_generated', 'AI Generated'), ('uploaded', 'Manual Upload'), ('unknown', 'Unknown')], default='unknown', help_text='Where the images came from (youtube, rss_original, pexels, uploaded)', max_length=20),
        ),
    ]
