# Generated by Django 6.0.1 on 2026-03-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0091_add_web_search_ai_generated_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reddit_enabled',
            field=models.BooleanField(default=False, help_text='Show Reddit link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reddit_url',
            field=models.URLField(blank=True),
        ),
    ]
