# Generated by Django 6.0.1 on 2026-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0092_add_reddit_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='External logo URL (fallback if no uploaded logo)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Official brand website'),
        ),
    ]
