# Generated by Django 6.0.1 on 2026-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0093_brand_add_logo_url_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_news_only',
            field=models.BooleanField(db_index=True, default=False, help_text='General news only. Exclude from specific Car Catalog brand/model pages.'),
        ),
    ]
