# Generated by Django 6.0.1 on 2026-03-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0094_article_is_news_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_make', models.CharField(db_index=True, max_length=100)),
                ('subject_model', models.CharField(db_index=True, max_length=100)),
                ('competitor_make', models.CharField(db_index=True, max_length=100)),
                ('competitor_model', models.CharField(db_index=True, max_length=100)),
                ('competitor_trim', models.CharField(blank=True, default='', max_length=100)),
                ('competitor_power_hp', models.IntegerField(blank=True, null=True)),
                ('competitor_range_km', models.IntegerField(blank=True, null=True)),
                ('competitor_price_usd', models.IntegerField(blank=True, null=True)),
                ('engagement_score_at_log', models.FloatField(blank=True, help_text='article.engagement_score captured 48h+ after publication', null=True)),
                ('engagement_scored_at', models.DateTimeField(blank=True, help_text='When engagement_score_at_log was last updated', null=True)),
                ('match_score', models.FloatField(default=0.0, help_text='How well this competitor matched at selection time (0-1)')),
                ('selection_method', models.CharField(choices=[('rule_based', 'Rule-Based (fuel+body+price)'), ('ml_ranked', 'ML-Ranked (engagement history)')], default='rule_based', help_text='How this competitor was selected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(help_text='Article that included these competitor comparisons', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_pair_logs', to='news.article')),
            ],
            options={
                'verbose_name': 'Competitor Pair Log',
                'verbose_name_plural': 'Competitor Pair Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_make', 'subject_model'], name='news_compet_subject_e40772_idx'), models.Index(fields=['competitor_make', 'competitor_model'], name='news_compet_competi_d0ea63_idx'), models.Index(fields=['-created_at'], name='news_compet_created_e30228_idx'), models.Index(fields=['engagement_score_at_log'], name='news_compet_engagem_e73887_idx')],
            },
        ),
    ]
