# Generated by Django 6.0.1 on 2026-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0095_add_competitor_pair_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletitlevariant',
            name='selected_at',
            field=models.DateTimeField(blank=True, help_text='When this variant was selected as winner (admin or auto)', null=True),
        ),
        migrations.AddField(
            model_name='articletitlevariant',
            name='selection_source',
            field=models.CharField(blank=True, choices=[('admin', 'Admin picked manually'), ('auto', 'Auto-picked by CTR'), ('ai', 'AI-recommended')], default='', help_text='How the winner was selected — for ML training signal', max_length=10),
        ),
        migrations.AddField(
            model_name='articletitlevariant',
            name='title_pattern',
            field=models.JSONField(blank=True, help_text='Pre-extracted title features for future ML pattern analysis', null=True),
        ),
    ]
