# Generated by Django 6.0.1 on 2026-03-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0096_ab_title_variant_winner_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='infinite_scroll_enabled',
            field=models.BooleanField(default=True, help_text='Enable infinite article loading on scroll'),
        ),
        migrations.CreateModel(
            name='ArticleCapsuleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accurate_specs', '📊 Accurate Specs'), ('well_written', '✍️ Well Written'), ('great_photos', '📸 Great Photos'), ('fair_review', '⚖️ Fair Review'), ('useful_info', '💡 Useful Info'), ('wrong_specs', '📊 Wrong Specs'), ('too_long', '✍️ Too Long'), ('need_photos', '📸 Need Photos'), ('missing_price', '💰 Missing Price'), ('inaccurate', '❌ Inaccurate')], max_length=20)),
                ('is_positive', models.BooleanField(help_text='Auto-set based on feedback_type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_feedback', to='news.article')),
            ],
            options={
                'verbose_name': 'Article Capsule Feedback',
                'verbose_name_plural': 'Article Capsule Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'feedback_type'], name='news_articl_article_d97456_idx'), models.Index(fields=['feedback_type', 'is_positive'], name='news_articl_feedbac_8acd69_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'feedback_type', 'ip_address'), name='unique_capsule_per_ip')],
            },
        ),
    ]
