# Generated by Django 6.0.1 on 2026-03-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0097_capsule_feedback_infinite_scroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('reformat', '✨ Reformat with AI'), ('re_enrich', '⚡ Re-enrich Specs'), ('regenerate', '🔄 Regenerate'), ('edit_save', '💾 Article Saved'), ('image_change', '🖼️ Image Changed'), ('publish', '📢 Published'), ('unpublish', '📝 Unpublished'), ('delete', '🗑️ Deleted')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(help_text='Base32-encoded TOTP secret', max_length=64)),
                ('is_confirmed', models.BooleanField(default=False, help_text='True after user verifies their first code')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='One-time backup codes (hashed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Devices',
            },
        ),
    ]
