# Generated by Django 6.0.1 on 2026-03-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0099_unique_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='Number of consecutive fetch failures'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='last_error',
            field=models.CharField(blank=True, default='', help_text='Last error message from feed fetch', max_length=500),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='last_successful_fetch',
            field=models.DateTimeField(blank=True, help_text='When this feed was last successfully fetched', null=True),
        ),
    ]
