# Generated by Django 6.0.1 on 2026-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0100_rssfeed_health_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnewsitem',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked as interesting by editor. Excluded from 7-day cleanup (kept 60 days). Used as ML signal.'),
        ),
    ]
