# Generated by Django 6.0.1 on 2026-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0102_rss_llm_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='enrichment_report',
            field=models.JSONField(blank=True, help_text='Last bulk_enrich run summary: last_run, articles_processed, tags_created, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='rssnewsitem',
            name='llm_score',
            field=models.SmallIntegerField(blank=True, db_index=True, help_text='Groq relevance score 0-100. Null = not yet scored.', null=True),
        ),
        migrations.AlterField(
            model_name='rssnewsitem',
            name='llm_score_reason',
            field=models.CharField(blank=True, default='', help_text="Short reason from LLM scorer (e.g. 'BYD battery reveal').", max_length=200),
        ),
        migrations.AlterField(
            model_name='rssnewsitem',
            name='source_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Number of different RSS sources covering the same story. ≥3 = hot topic.'),
        ),
    ]
