# Generated by Django 6.0.1 on 2026-03-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0104_add_webauthn_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_channel_id',
            field=models.CharField(blank=True, default='@freshmotors_news', help_text='Telegram channel username or numeric chat_id', max_length=100),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Auto-post new articles to Telegram channel'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_last_run',
            field=models.DateTimeField(blank=True, help_text='When last Telegram post was sent', null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_last_status',
            field=models.CharField(blank=True, default='', help_text='Last post result', max_length=500),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_post_with_image',
            field=models.BooleanField(default=True, help_text='Try to attach article image to Telegram post'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='telegram_today_count',
            field=models.IntegerField(default=0, help_text='Posts sent today'),
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('reddit', 'Reddit')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('message_text', models.TextField(blank=True, help_text='Formatted post text')),
                ('external_id', models.CharField(blank=True, default='', help_text='Telegram message_id, tweet_id, etc.', max_length=100)),
                ('channel_id', models.CharField(blank=True, default='', help_text='Target channel/account', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='news.article')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_social_created_d6ac21_idx'), models.Index(fields=['platform', 'status'], name='news_social_platfor_295a3b_idx')],
            },
        ),
    ]
