# Generated by Django 6.0.1 on 2026-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0105_social_publishing_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_publish_skip_with_warnings',
            field=models.BooleanField(default=True, help_text='Skip articles with ⚠️ AI Fact-Check Warning banners — require manual review'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='youtube_active_hours_end',
            field=models.IntegerField(default=22, help_text='Hour to STOP YouTube scans (Israel time, 0-23). Default: 10 PM'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='youtube_active_hours_start',
            field=models.IntegerField(default=7, help_text='Hour to START YouTube scans (Israel time, 0-23). Default: 7 AM'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='youtube_daytime_only',
            field=models.BooleanField(default=True, help_text='Only run YouTube scans during active hours (saves API costs at night)'),
        ),
        migrations.AlterField(
            model_name='autopublishlog',
            name='decision',
            field=models.CharField(choices=[('published', 'Published'), ('drafted', 'Drafted (Awaiting Review)'), ('human_approved', 'Human Approved'), ('human_rejected', 'Human Rejected'), ('skipped_quality', 'Skipped: Low Quality'), ('skipped_safety', 'Skipped: Feed Unsafe'), ('skipped_no_image', 'Skipped: No Image'), ('skipped_warnings', 'Skipped: Fact-Check Warning'), ('skipped_limit', 'Skipped: Rate Limit'), ('skipped_duplicate', 'Skipped: Too Similar'), ('failed', 'Failed: Error')], max_length=30),
        ),
    ]
