# Generated by Django 6.0.1 on 2026-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0106_youtube_daytime_and_autopublish_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingarticle',
            name='seo_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Separate from excerpt/summary.', max_length=160),
        ),
    ]
