# Generated by Django 6.0.1 on 2026-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0108_add_curator_decision_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='curatordecisionlog',
            new_name='news_curato_decisio_815b92_idx',
            old_name='news_curato_decisio_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, auto-publish at this time (flips is_published=True and clears this field)', null=True),
        ),
    ]
