# Generated by Django 6.0.1 on 2026-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0113_article_moderation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trainingpair',
            new_name='news_traini_pair_ty_373ddd_idx',
            old_name='news_traini_pair_ty_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this article was last bulk-enriched (Deep Specs + AB Titles + Tags)', null=True),
        ),
    ]
