# Generated by Django 6.0.1 on 2026-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0114_add_last_enriched_at_to_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_enabled',
            field=models.BooleanField(default=False, help_text="Auto-generate 'X vs Y' comparison articles weekly"),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_last_run',
            field=models.DateTimeField(blank=True, help_text='When comparison auto-generation last ran', null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_last_status',
            field=models.CharField(blank=True, default='', help_text='Last comparison generation result', max_length=500),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_max_per_week',
            field=models.IntegerField(default=2, help_text='Max comparison articles to generate per week (2-5)'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_provider',
            field=models.CharField(default='gemini', help_text='AI provider for comparison generation: gemini or groq', max_length=20),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_this_week_count',
            field=models.IntegerField(default=0, help_text='Comparisons generated this week'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='comparison_week_start',
            field=models.DateField(blank=True, help_text='Start of current comparison week (for weekly reset)', null=True),
        ),
    ]
