# Generated by Django 6.0.1 on 2026-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0115_add_comparison_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='auto_publish_min_score',
            field=models.IntegerField(default=0, help_text='Minimum AI Quality Score (0-100) required to auto-publish articles from this feed.'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='exclude_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords. If set, article will be skipped if it contains any of these.'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='include_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords. If set, article MUST contain at least one to be saved.'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='scan_frequency',
            field=models.IntegerField(choices=[(15, '15 Minutes'), (60, '1 Hour'), (360, '6 Hours'), (720, '12 Hours'), (1440, '24 Hours')], default=720, help_text='How often to automatically scan this feed (in minutes)'),
        ),
    ]
