# Generated by Django 6.0.1 on 2026-03-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0116_rssfeed_auto_publish_min_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideoCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('view_count', models.IntegerField(blank=True, help_text='YouTube view count at scan time', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Video publish date on YouTube', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_candidates', to='news.youtubechannel')),
            ],
            options={
                'verbose_name': 'YouTube Video Candidate',
                'verbose_name_plural': 'YouTube Video Candidates',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='news_youtub_status_60f20a_idx'), models.Index(fields=['channel', '-published_at'], name='news_youtub_channel_926f15_idx')],
            },
        ),
    ]
