# Generated by Django 6.0.1 on 2026-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0117_youtube_video_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideocandidate',
            name='generation_error',
            field=models.CharField(blank=True, default='', help_text='Last generation error message', max_length=500),
        ),
        migrations.AddField(
            model_name='youtubevideocandidate',
            name='generation_task_id',
            field=models.CharField(blank=True, default='', help_text='Background task ID for article generation', max_length=100),
        ),
        migrations.AlterField(
            model_name='youtubevideocandidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('generating', 'Generating'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20),
        ),
    ]
