# Generated by Django 6.0.1 on 2026-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0118_add_generation_tracking_to_video_candidate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlegscstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='is_partner',
            field=models.BooleanField(default=False, help_text="Partner feed — we have explicit permission to use their content. Shows 'Special thanks' instead of 'Source' at the bottom of articles."),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='is_partner',
            field=models.BooleanField(default=False, help_text="Partner channel — we have explicit permission to use their content. Shows 'Special thanks' instead of 'Source' at the bottom of articles."),
        ),
        migrations.AddConstraint(
            model_name='articlegscstats',
            constraint=models.UniqueConstraint(fields=('article', 'date'), name='unique_article_gsc_per_date'),
        ),
    ]
