# Generated by Django 6.0.1 on 2026-03-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0119_add_is_partner_to_channel_and_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnewsitem',
            name='content_type',
            field=models.CharField(choices=[('review', 'Review / Test Drive'), ('debut', 'Debut / Reveal'), ('news', 'News / Update'), ('noise', 'Noise / Recall / Legal'), ('general', 'General')], db_index=True, default='general', help_text='Auto-classified content type based on title/excerpt keywords.', max_length=20),
        ),
    ]
