# Generated by Django 6.0.1 on 2026-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0120_add_content_type_to_rssnewsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclespecs',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('EV', 'Electric Vehicle'), ('Hybrid', 'Hybrid'), ('PHEV', 'Plug-in Hybrid'), ('EREV', 'Extended Range EV'), ('Gas', 'Gasoline'), ('Diesel', 'Diesel'), ('Hydrogen', 'Hydrogen')], help_text='Fuel/power source type', max_length=20, null=True),
        ),
    ]
