# Generated by Django 6.0.1 on 2026-03-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0121_add_erev_fuel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCompetitorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_make', models.CharField(db_index=True, max_length=100)),
                ('subject_model', models.CharField(db_index=True, max_length=100)),
                ('competitor_make', models.CharField(db_index=True, max_length=100)),
                ('competitor_model', models.CharField(db_index=True, max_length=100)),
                ('score', models.FloatField(db_index=True, help_text='1.0 = Perfect match, 0.5 = Acceptable, -1.0 = Bad match')),
                ('penalty_reason', models.CharField(blank=True, help_text='Tag explaining a negative score (price, body_type, fuel_type, prestige)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_competitor_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Competitor Feedback',
                'verbose_name_plural': 'Manual Competitor Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_make', 'subject_model'], name='news_manual_subject_8270f5_idx'), models.Index(fields=['competitor_make', 'competitor_model'], name='news_manual_competi_8b3c90_idx')],
            },
        ),
    ]
